[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "datamining"
version = "0.0.0"

[tool.setuptools.packages.find]
include = ["datamining*"]